apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-deployment
  labels:
    app: ems-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-app
  template:
    metadata:
      labels:
        app: ems-app
    spec:
      containers:
      - name: ems
        image: shashanktyagi/ems-app:a04f4d70592849e283c5ae425523e88cdf957087_12
        ports:
        - containerPort: 8080
