apiVersion: apps/v1
kind: Deployment
metadata:
  name: EMS-deployment
  labels:
    app: ems-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-app
  template:
    metadata:
      labels:
        app: ems-app
    spec:
      containers:
      - name: ems
        image: ems-app
        ports:
        - containerPort: 8080
