---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-deployment
  labels:
    app: ems-app
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-app
  template:
    metadata:
      labels:
        app: ems-app
    spec:
      containers:
      - name: ems
        image: shashanktyagi/ems-app:0ffeabc567fcf80dba2ce5d190d822a658d46adf_13
        ports:
        - containerPort: 8080
